/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 0.8.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// Unprocessable entity
type DeleteCharactersCharacterIdMailLabelsLabelIdUnprocessableEntity struct {

	// Unprocessable entity message
	Error_ string `json:"error,omitempty"`
}
