/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 0.8.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// Error 520
type GetCorporationsCorporationIdContractsContractIdItemsError520 struct {

	// Error 520 message
	Error_ string `json:"error,omitempty"`
}
