/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 0.8.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// service object
type GetCorporationsCorporationIdStructuresService struct {

	// name string
	Name string `json:"name"`

	// state string
	State string `json:"state"`
}
