/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 0.8.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// Not found
type GetContractsPublicItemsContractIdNotFound struct {

	// Not found message
	Error_ string `json:"error,omitempty"`
}
