/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 0.8.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// character_id and response of an attendee
type GetCharactersCharacterIdCalendarEventIdAttendees200Ok struct {

	// character_id integer
	CharacterId int32 `json:"character_id,omitempty"`

	// event_response string
	EventResponse string `json:"event_response,omitempty"`
}
