/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// Not found
type GetDogmaEffectsEffectIdNotFound struct {

	// Not found message
	Error_ string `json:"error,omitempty"`
}
