/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.2.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// required_item object
type GetLoyaltyStoresCorporationIdOffersRequiredItem struct {

	// quantity integer
	Quantity int32 `json:"quantity"`

	// type_id integer
	TypeId int32 `json:"type_id"`
}
