/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 0.8.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// 200 ok object
type GetUniverseAsteroidBeltsAsteroidBeltIdOk struct {

	// name string
	Name string `json:"name"`

	Position *GetUniverseAsteroidBeltsAsteroidBeltIdPosition `json:"position"`

	// The solar system this asteroid belt is in
	SystemId int32 `json:"system_id"`
}
