/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 0.8.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// level object
type GetInsurancePricesLevel struct {

	// cost number
	Cost float32 `json:"cost"`

	// Localized insurance level
	Name string `json:"name"`

	// payout number
	Payout float32 `json:"payout"`
}
