/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 0.8.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// 201 created object
type PostFleetsFleetIdWingsCreated struct {

	// The wing_id of the newly created wing
	WingId int64 `json:"wing_id"`
}
