/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 0.8.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// station object
type PostUniverseIdsStation struct {

	// id integer
	Id int32 `json:"id,omitempty"`

	// name string
	Name string `json:"name,omitempty"`
}
