/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 0.8.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// naming object
type PutFleetsFleetIdSquadsSquadIdNaming struct {

	// name string
	Name string `json:"name"`
}
