/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 0.8.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// response object
type PutCharactersCharacterIdCalendarEventIdResponse struct {

	// response string
	Response string `json:"response"`
}
