/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 0.8.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// 422 unprocessable entity object
type PutFleetsFleetIdMembersMemberIdUnprocessableEntity struct {

	// error message
	Error_ string `json:"error,omitempty"`
}
