/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.2.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package esi

// Unauthorized model
type Unauthorized struct {

	// Unauthorized message
	Error_ string `json:"error"`
}
